version: '3.6'
services:
  mongo:
    image: mongo:4.0.10-xenial
    container_name: mongo_pusher_container
    networks:
      pusher:
        aliases:
          - mongodb
          - documentstorage
    ports:
      - "8082:8081"
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: pusher_user
      MONGO_INITDB_ROOT_PASSWORD: pusher_pass
      MONGO_INITDB_DATABASE: pusher_db

  pusher:
    build: .
    image: pusher
    container_name: pusher_back_end
    networks:
      pusher:
        aliases:
          - pusher
    ports:
      - "8000:8000"

volumes:
  mongo_data:
  data:

networks:
  pusher:
    driver: bridge
    name: pusher

